MyAveiro/Controllers/FoodTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class FoodTypesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();
        
        // GET: FoodTypes/Restaurants
        public ActionResult Restaurants()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Food" && i.FoodTypes.FoodTypeName == "Restaurant").ToList());
        }

      
        // GET: FoodTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

    }
}

MyAveiro/Controllers/FunTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class FunTypesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();


        // GET: FunTypes/Museum
        public ActionResult Museum()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Museum").ToList());
        }

    
        // GET: FunTypes/Beach
        public ActionResult Beach()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Beach").ToList());
        }

        
        // GET: FunTypes/OutdoorActivities
        public ActionResult OutdoorActivities()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Outdoor Activities").ToList());
        }

        // GET: FunTypes/BarsPubs
        public ActionResult BarsPubs()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Bars & Pubs").ToList());
        }

        // GET: FunTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

        

    }
}

MyAveiro/Controllers/RestTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class RestTypesController : Controller
	{
        private MyAveiroContext db = new MyAveiroContext();

        // GET: RestTypes/Hostels
        public ActionResult Hostels()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Rest" && i.RestTypes.RestTypeName == "Hostel").ToList());
        }
        
        // GET: RestTypes/Hotels
        public ActionResult Hotels()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Rest" && i.RestTypes.RestTypeName == "Hotel").ToList());
        }

        // GET: RestTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }
	}
}

MyAveiro/Controllers/UtilitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyAveiro.DAL;
using MyAveiro.Models;

namespace MyAveiro.Controllers
{
    public class UtilitiesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();

        // GET: Utilities
        public ActionResult Index()
        {
            return View(db.Utilities.ToList());
        }
       
        // GET: Utilities/Emergency
        public ActionResult Emergency()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Emergency").ToList());
        }

        // GET: Utilities/Transports
        public ActionResult Transports()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Transport").ToList());
        }

        // GET: Utilities/Police
        public ActionResult Police()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Police").ToList());
        }

        // GET: Utilities/Rest
        public ActionResult Rest()
        {

            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Rest").ToList().Distinct());
        }

        // GET: Utilities/Food
        public ActionResult Food()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Food").ToList());
        }

        // GET: Utilities/Fun
        public ActionResult Fun()
        {
            return View(db.Utilities.Where(i=>i.UtilitiesTypes.UtilityTypeName=="Fun").ToList());
        }

        // GET: Utilities/Events
        public ActionResult Events()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Event").ToList());
        }

        // GET: Utilities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

         public ActionResult ImagesRepositoryPartial(string Acronym)
        {
            List<String> listImagemRepository = GetAvailableImagesFromRepository(Acronym);
            return PartialView("_ImageDetails", listImagemRepository);

        }

        public List<string> GetAvailableImagesFromRepository(string Acronym)
        {
            if (Acronym != null && Acronym != string.Empty)
                return db.ImagesRepository.Where(i => i.Utilities.Acronym == Acronym).Select(i => i.URLImage).ToList();
            else
                return new List<string>();
        }
    }
}

MyAveiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Include jQuery lib for AJAX requests -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <!-- Include google map lib -->
    <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyAveiro - @ViewBag.Title</title>

    <!-- Bootstrap -->
   <link href="@Url.Content("/Content/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/Content/modern-business.css")" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("MyAveiro", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">

                    <li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quick Links <b class="caret"></b></a>
                        <ul class="dropdown-menu">

                            <li id="sidebarpage">
                                @Html.ActionLink("Transports", "Transports", "Utilities")
                                @Html.ActionLink("Emergency", "Emergency", "Utilities")
                                @Html.ActionLink("Police", "Police", "Utilities")
                            </li>

                        </ul>
                    </li>

                </ul>
            </div>

        </div>

    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; MyAveiro</p>
                </div>
            </div>
        </footer>

    </div>
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>
  

MyAveiro/Views/Shared/_SideBar.cshtml
<div class="col-md-3 col-sm-4 sidebar">
    <ul class="nav nav-stacked nav-pills">
        
        <li class="disabled">
            @Html.ActionLink("Rest in Aveiro", "Index", "Home")
        </li>
        <li>
            @Html.ActionLink("Interest Points", "Aveiro", "Home")
        </li>
        <li class="disabled">
            @Html.ActionLink("Rest in Aveiro", "Rest", "Utilities")
        </li>
        <li>
            @Html.ActionLink("Hotel", "Hotels", "RestTypes")
        </li>
        <li>
            @Html.ActionLink("Hostel", "Hostels", "RestTypes")
        </li>
        <li class="disabled">
            @Html.ActionLink("Food in Aveiro", "Food", "Utilities")
        </li>
        <li>
            @Html.ActionLink("Restaurants", "Restaurants", "FoodTypes")
        </li>
        <li class="disabled">
            @Html.ActionLink("Fun in Aveiro", "Fun", "Utilities")
        </li>
        <li>
            @Html.ActionLink("Bars & Pubs", "BarsPubs", "FunTypes")
        </li>
        <li>
            @Html.ActionLink("Beach", "Beach", "FunTypes")
        </li>
        <li>
            @Html.ActionLink("Museum", "Museum", "FunTypes")
        </li>
        <li>
            @Html.ActionLink("Outdoor Activities", "OutdoorActivities", "FunTypes")
        </li>
        <li class="disabled">
            @Html.ActionLink("Events in Aveiro", "Events", "Utilities")
        </li>
        <li>
            @Html.ActionLink("Exhibitions", "Exhibitions", "EventTypes")
        </li>
    </ul>
</div>