MyAveiro/Models/EventTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAveiro.Models
{
    public class EventTypes
    {
        public int ID { get; set; }
        public string EventTypeName { get; set; }
    }
}

MyAveiro/Models/FoodTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAveiro.Models
{
    public class FoodTypes
    {
        public int ID { get; set; }
        public string FoodTypeName { get; set; }
    }
}

MyAveiro/Models/FunTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAveiro.Models
{
    public class FunTypes
    {
        public int ID { get; set; }
        public string FunTypeName { get; set; }
    }
}

MyAveiro/Models/RestTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAveiro.Models
{
    public class RestTypes
    {
        public int ID { get; set; }
        public string RestTypeName { get; set; }
    }
}

MyAveiro/Models/UtilitiesTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAveiro.Models
{
    public class UtilitiesTypes
    {
        public int ID { get; set; }
        public string UtilityName { get; set; }
    }
}

MyAveiro/Controllers/EventTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class EventTypesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();

        // GET: EventTypes/Exhibitions
        public ActionResult Exhibitions()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Event" && i.EventTypes.EventTypeName == "Exhibitions").ToList());
        }

       
        // GET: EventTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

    }
}

MyAveiro/Controllers/FoodTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class FoodTypesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();
        
        // GET: FoodTypes/Restaurants
        public ActionResult Restaurants()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Food" && i.FoodTypes.FoodTypeName == "Restaurant").ToList());
        }

      
        // GET: FoodTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

    }
}

MyAveiro/Controllers/FunTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class FunTypesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();


        // GET: FunTypes/Museum
        public ActionResult Museum()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Museum").ToList());
        }

    
        // GET: FunTypes/Beach
        public ActionResult Beach()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Beach").ToList());
        }

        
        // GET: FunTypes/OutdoorActivities
        public ActionResult OutdoorActivities()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Outdoor Activities").ToList());
        }

        // GET: FunTypes/BarsPubs
        public ActionResult BarsPubs()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Fun" && i.FunTypes.FunTypeName == "Bars & Pubs").ToList());
        }

        // GET: FunTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

        

    }
}

MyAveiro/Controllers/RestTypesController.cs
using MyAveiro.DAL;
using MyAveiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyAveiro.Controllers
{
    public class RestTypesController : Controller
	{
        private MyAveiroContext db = new MyAveiroContext();

        // GET: RestTypes/Hostels
        public ActionResult Hostels()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Rest" && i.RestTypes.RestTypeName == "Hostel").ToList());
        }
        
        // GET: RestTypes/Hotels
        public ActionResult Hotels()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Rest" && i.RestTypes.RestTypeName == "Hotel").ToList());
        }

        // GET: RestTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }
	}
}

MyAveiro/Controllers/UtilitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyAveiro.DAL;
using MyAveiro.Models;

namespace MyAveiro.Controllers
{
    public class UtilitiesController : Controller
    {
        private MyAveiroContext db = new MyAveiroContext();

        // GET: Utilities
        public ActionResult Index()
        {
            return View(db.Utilities.ToList());
        }
       
        // GET: Utilities/Emergency
        public ActionResult Emergency()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Emergency").ToList());
        }

        // GET: Utilities/Transports
        public ActionResult Transports()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Transport").ToList());
        }

        // GET: Utilities/Police
        public ActionResult Police()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Police").ToList());
        }

        // GET: Utilities/Rest
        public ActionResult Rest()
        {

            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Rest").ToList().Distinct());
        }

        // GET: Utilities/Food
        public ActionResult Food()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Food").ToList());
        }

        // GET: Utilities/Fun
        public ActionResult Fun()
        {
            return View(db.Utilities.Where(i=>i.UtilitiesTypes.UtilityTypeName=="Fun").ToList());
        }

        // GET: Utilities/Events
        public ActionResult Events()
        {
            return View(db.Utilities.Where(i => i.UtilitiesTypes.UtilityTypeName == "Event").ToList());
        }

        // GET: Utilities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilities utilities = db.Utilities.Find(id);
            if (utilities == null)
            {
                return HttpNotFound();
            }
            return View(utilities);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

         public ActionResult ImagesRepositoryPartial(string Acronym)
        {
            List<String> listImagemRepository = GetAvailableImagesFromRepository(Acronym);
            return PartialView("_ImageDetails", listImagemRepository);

        }

        public List<string> GetAvailableImagesFromRepository(string Acronym)
        {
            if (Acronym != null && Acronym != string.Empty)
                return db.ImagesRepository.Where(i => i.Utilities.Acronym == Acronym).Select(i => i.URLImage).ToList();
            else
                return new List<string>();
        }
    }
}

MyAveiro/Views/Utilities/Details.cshtml
@*@model MyAveiro.Models.Utilities

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Utilities</h4>
    <hr />
    <dl class="dl-horizontal">
       

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acronym)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acronym)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URLSite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URLSite)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

MyAveiro/Views/Utilities/Emergency.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Emergency List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Emergency
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Phone")
                    </th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150px" height="100px">
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </th>
                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/Events.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Food List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Event
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150px" height="100px">
                        </td>

                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "EventTypes", new { id = item.ID }, null)
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/Food.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Food List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Food
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150px" height="100px">
                        </td>

                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "FoodTypes", new { id = item.ID }, null)
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/Fun.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Fun List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Fun
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150px" height="100px">
                        </td>

                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "FunTypes", new { id = item.ID }, null)
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/Index.cshtml
@*@model IEnumerable<MyAveiro.Models.Utilities>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Acronym)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URLSite)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Acronym)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.URLSite)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>*@

MyAveiro/Views/Utilities/Police.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Police List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Police
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Phone")
                    </th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150" height="100">
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </th>
                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/Rest.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Rest List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Rest
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150px" height="100px">
                        </td>

                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "RestTypes",new { id = item.ID }, null)
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/Transports.cshtml
@model IEnumerable<MyAveiro.Models.Utilities>
@{
    ViewBag.Title = "Transports List";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/Shared/_SideBar.cshtml")

        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Transports
                <small> List</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Main Page", "Index", "Home")

                </li>
            </ol>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Name")
                    </th>
                    <th>
                        @Html.DisplayName("Address")
                    </th>
                    <th></th>
                    <th>
                        @Html.DisplayName("Phone")
                    </th>
                    <th>
                        @Html.DisplayName("Web Site")
                    </th>
                   
                </tr>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            <img src="@Url.Content(item.URLImg)" alt="Not found" width="150" height="100">
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                        <td>
                            <a href="@Url.Content(item.URLSite)">Visit</a>

                        </td>
                        
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

MyAveiro/Views/Utilities/_ImageDetails.cshtml
@model System.Collections.Generic.IEnumerable<string>

<!-- Icones used in the carousel -->
<div id="myCarousel" class="carousel" data-ride="carousel" style="margin-left:20px;">
    <!-- Icones used in the carousel -->
    <ol class="carousel-indicators">
        @*<li data-target="#myCarousel" data-slide-to="3"></li>*@
        @for (int i = 0; i < 1; i++)
        {
            <li data-target="#myCarousel" data-slide-to="@i" class="active"></li>
        }
        @for (int i = 1; i < Model.Count(); i++)
        {
            <li data-target="#myCarousel" data-slide-to="@i"></li>
        }
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        @foreach (var item in Model)
        {
            <div class="item active">
                <img src="@Url.Content(@item)" >
            </div>
            break;
        }
        @for (int i = 1; i < Model.Count(); i++)
        {
            <div class="item ">
                <img src="@Url.Content(Model.ElementAt(i))" >
            </div>
        }
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>